### ISSUE TITLE
[feature request] Add  "Use this:" option for all custom fields.

### ISSUE THREAD

**Issue by tracure1337** [calvinballing/fake-filler-extension#3]
![image](https://github.com/calvinballing/fake-filler-extension/assets/43231640/d97aed8b-ad59-43bc-85ad-bcec094ebc4e)

This is great but it's not possible to do this for other fields like username where I always want "dummyuser" for example.

Thanks for your consideration.

**Comment by calvinballing** [comment]
This can currently be accomplished via custom fields, by setting rules to match username fields and limiting the fill value to your preferred string.  Let me know if you’d like a more detailed explanation

**Comment by calvinballing** [comment]
To build on that a bit, something like this should do the trick:

1. Open Fake Filler 2 settings
2. Click `Custom Fields`
![Screen Shot 2024-03-25 at 9 20 22 AM](https://github.com/calvinballing/fake-filler-extension/assets/5534029/0630ec64-86cd-43ab-8d1e-4f8658447be1)

3. Edit the existing Username matching field, and change it to, for example `Regular Expression`, `dummyuser`
![Screen Shot 2024-03-25 at 9 21 29 AM](https://github.com/calvinballing/fake-filler-extension/assets/5534029/84cdb51e-a7e2-493d-b7a4-9a791350c07c)

**Comment by tracure1337** [comment]
@calvinballing   Thank  you very  much!
